spring.application.name=gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.mvc.routes[0].id=movie-file
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8085
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/movie-details/*

spring.cloud.gateway.mvc.routes[1].id=movie
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8093
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/stream/*